import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: '#8e4922',
        'primary-container': '#ac6138',
        'primary-fixed': '#ffdbcb',
        'primary-fixed-dim': '#ffb691',
        'on-primary': '#ffffff',
        'on-primary-container': '#fffbff',
        'on-primary-fixed': '#341100',
        'on-primary-fixed-variant': '#73350f',
        'inverse-primary': '#ffb691',

        secondary: '#805529',
        'secondary-container': '#fdc48e',
        'secondary-fixed': '#ffdcbf',
        'secondary-fixed-dim': '#f4bb86',
        'on-secondary': '#ffffff',
        'on-secondary-container': '#784f23',
        'on-secondary-fixed': '#2d1600',
        'on-secondary-fixed-variant': '#653e14',

        tertiary: '#4f6149',
        'tertiary-container': '#687a61',
        'tertiary-fixed': '#d5e8ca',
        'tertiary-fixed-dim': '#b9ccaf',
        'on-tertiary': '#ffffff',
        'on-tertiary-container': '#f8fff0',
        'on-tertiary-fixed': '#101f0d',
        'on-tertiary-fixed-variant': '#3a4b35',

        surface: '#fff8f5',
        'surface-bright': '#fff8f5',
        'surface-dim': '#ecd6c8',
        'surface-tan': '#EEE2D4',
        'surface-tint': '#914c24',
        'surface-variant': '#f5ded0',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#fff1e9',
        'surface-container': '#ffeadd',
        'surface-container-high': '#fae4d5',
        'surface-container-highest': '#f5ded0',

        background: '#fff8f5',
        'background-cream': '#F8F3EE',
        'on-background': '#241911',
        'on-surface': '#241911',
        'on-surface-variant': '#54433c',
        'inverse-surface': '#3b2e24',
        'inverse-on-surface': '#ffede3',

        'body-text': '#5E5147',
        'border-muted': '#DDD4CA',
        outline: '#86736a',
        'outline-variant': '#d9c2b7',

        error: '#ba1a1a',
        'error-container': '#ffdad6',
        'on-error': '#ffffff',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1320px',
        gutter: '24px',
        'margin-desktop': '64px',
        'margin-mobile': '20px',
        'section-gap': '96px',
      },
      fontFamily: {
        display: ['var(--font-cormorant)', 'serif'],
        headline: ['var(--font-cormorant)', 'serif'],
        body: ['var(--font-manrope)', 'sans-serif'],
        label: ['var(--font-manrope)', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-xl': ['56px', { lineHeight: '64px', fontWeight: '500' }],
        'headline-lg': ['36px', { lineHeight: '44px', fontWeight: '500' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'title-md': ['24px', { lineHeight: '32px', letterSpacing: '0.01em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-sm': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['14px', { lineHeight: '20px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};

export default config;
